### ISSUE TITLE
Docker image missing rubygems

### ISSUE THREAD

**Issue by ehsandeep** [menzow/sn1per-docker#1]
![image](https://cloud.githubusercontent.com/assets/8293321/25058419/c5738294-2196-11e7-93bb-70d8fa137531.png)

````
+ -- ----------------------------=[Scanning For Common Vulnerabilities]=----- -- +
/usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require': cannot load such file -- sqlite3 (LoadError)
        from /usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
        from yasuo.rb:34:in `<main>'
````

**Comment by menzow** [comment]
Hello @s4ndeeps ,

Thank you for reporting this issue. A new image will be available later today.

**Comment by ehsandeep** [comment]
is it fixed in new release ?

**Comment by menzow** [comment]
Hey @s4ndeeps ,

Just to confirm; yes this has been fixed in the latest release. Please install the latest version by running `docker pull menzo/sn1per-docker:latest`.
